[package]
name = "rustball"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.12"
rand = "0.8"

[dependencies.bevy_rapier2d]
version = "0.24"
features = [ "default",]

[dependencies.tokio]
version = "1.38"
features = [ "full",]
